library(mlmRev)
options(show.signif.stars = FALSE)
(fm01 <- lmer(langPOST ~ IQ.ver.cen+avg.IQ.ver.cen+(1|schoolNR), bdf))
(fm02 <- lmer(langPOST ~ IQ.ver.cen+avg.IQ.ver.cen+(IQ.ver.cen|schoolNR), bdf))
(fm03 <- lmer(math ~ year+(1|childid)+(1|schoolid), egsingle))
(fm04 <- lmer(math ~ year+(1|childid)+(year|schoolid), egsingle))
(fm05 <- lmer(normexam ~ standLRT + sex + schgend + (1|school), Exam))
(fm06 <- lmer(score ~ gcsecnt + (1|school) + (1|lea), Chem97))
(fm07 <- lmer(height ~ age + I(age^2) + I(age^3) + I(age^4) + (age + I(age^2)|Subject),
                 Oxboys))
(fm08 <- lmer(height ~ poly(age,4) + (age + I(age^2)|Subject), Oxboys))
(fm09 <- lmer(attain ~ verbal * sex+(1|primary)+(1|second), ScotsSec))
(fm10 <- lmer(attain ~ verbal + sex+(1|primary)+(sex|second), ScotsSec))
