lme4: lmer.h File Reference
lmer.h File Reference
#include <R.h>
#include <Rdefines.h>
Functions
SEXP lme4_rWishart (SEXP ns, SEXP dfp, SEXP scal)
Simulate a sample of random matrices from a Wishart distribution.
SEXP mer_condMode (SEXP x, SEXP verbP)
Externally callable version of cond_mode.
SEXP mer_create_L (SEXP Vt)
Create and initialize L.
SEXP mer_create_Vt (SEXP Zt, SEXP ST, SEXP Gp)
Create the Vt matrix pattern from Zt, ST and Gp.
SEXP mer_MCMCsamp (SEXP x, SEXP savebp, SEXP nsampp, SEXP transp, SEXP verbose, SEXP deviance)
Generate a Markov-Chain Monte Carlo sample from a fitted linear mixed model.
SEXP mer_optimize (SEXP x, SEXP verb)
Optimize the profiled deviance of an lmer object or the Laplace approximation to the deviance of a nlmer or glmer object.
SEXP mer_postVar (SEXP x, SEXP useScale)
Extract the posterior variances of the random effects in an lmer object.
SEXP mer_profiled_deviance (SEXP x)
Externally callable version of profiled_deviance.
SEXP mer_sigma (SEXP x, SEXP which)
Extract the estimate of the common scale factor from an mer object.
SEXP mer_ST_getPars (SEXP x)
Extract the parameters from the ST slot of an mer object.
SEXP mer_ST_initialize (SEXP ST, SEXP Gp, SEXP Zt)
Evaluate starting estimates for the elements of ST.
SEXP mer_ST_setPars (SEXP x, SEXP pars)
Update the ST slot of an mer object from a REAL vector of parameters and update the Cholesky factorization.
SEXP mer_update_dev (SEXP x)
Evaluate the discrepancy and log of the penalized discrepancy.
SEXP mer_update_effects (SEXP x)
Update the contents of the fixef, ranef and uvec slots in an lmer object.
SEXP mer_update_L (SEXP x)
Externally callable version of update_L.
SEXP mer_update_mu (SEXP x)
Externally callable update_mu.
SEXP mer_validate (SEXP x)
Check validity of an object that inherits from the mer class.
SEXP nlmer_create_A (SEXP Vt, SEXP sP)
Create the dgCMatrix object A.
SEXP pedigree_chol (SEXP x, SEXP ans)
Create the left Cholesky factor of the numerator relationship matrix from a pedigree.
Function Documentation
SEXP lme4_rWishart (SEXP ns, SEXP dfp, SEXP scal)
Simulate a sample of random matrices from a Wishart distribution.
Parameters:
ns Number of samples to generate
dfp Degrees of freedom
scal Positive-definite scale matrix
Returns:
Definition at line 1359 of file lmer.c.
References Alloca, AZERO, and std_rWishart_factor().
SEXP mer_condMode (SEXP x, SEXP verbP)
Externally callable version of cond_mode.
Iterate to determine the conditional modes of the random effects.
Parameters:
x pointer to an mer object
verbP scalar integer indicator of verbose output (negative values produce a lot of output)
Returns:
number of iterations to convergence (0 for non-convergence)
Definition at line 1005 of file lmer.c.
References cond_mode().
SEXP mer_create_L (SEXP Vt)
Create and initialize L.
Parameters:
Vt pointer to the model matrix for the orthogonal random effects (transposed)
Returns:
L
Definition at line 640 of file lmer.c.
References _, and c.
SEXP mer_create_Vt (SEXP Zt, SEXP ST, SEXP GpP)
Create the Vt matrix pattern from Zt, ST and Gp.
Partition the columns into s groups and overlay them.
Parameters:
Zt
ST
GpP pointer to the Gp array
Returns:
Vt
Definition at line 1130 of file lmer.c.
References Alloca, AZERO, lme4_DimNamesSym, lme4_DimSym, lme4_iSym, lme4_pSym, lme4_xSym, ST_nc_nlev(), and Vt_nz_col().
SEXP mer_MCMCsamp (SEXP x, SEXP savebp, SEXP nsampp, SEXP transp, SEXP verbosep, SEXP deviancep)
Generate a Markov-Chain Monte Carlo sample from a fitted linear mixed model.
Parameters:
x pointer to an lmer object
savebp logical scalar - save random effects?
nsampp integer scalar - number of samples to generate
transp logical scalar - transform variance components?
verbosep logical scalar - verbose output?
deviancep logical scalar - store the deviance?
Returns:
a matrix
Definition at line 1542 of file lmer.c.
References lme4_devianceSym, lme4_dimsSym, lme4_fixefSym, lme4_ranefSym, lpdisc_POS, mer_MCMC_betab(), mer_MCMC_ST(), mer_ST_getPars(), mer_ST_setPars(), mer_update_effects(), ML_POS, n_POS, np_POS, p_POS, q_POS, and REML_POS.
SEXP mer_optimize (SEXP x, SEXP verbp)
Optimize the profiled deviance of an lmer object or the Laplace approximation to the deviance of a nlmer or glmer object.
Parameters:
x pointer to an mer object
verbp pointer to indicator of verbose output
Returns:
R_NilValue
Definition at line 1259 of file lmer.c.
References Alloca, cond_mode(), cvg_POS, lme4_devianceSym, lme4_dimsSym, lme4_fixefSym, lme4_muEtaSym, lme4_STSym, lme4_vSym, mer_update_dev(), ML_POS, nf_POS, np_POS, p_POS, profiled_deviance(), ST_getPars(), and ST_setPars().
SEXP mer_postVar (SEXP x, SEXP uS)
Extract the posterior variances of the random effects in an lmer object.
Parameters:
x pointer to an lmer object
uS logical scalar indicating whether to use the common scale
Returns:
pointer to a list of arrays
Definition at line 576 of file lmer.c.
References Alloca, c, isREML, L_SLOT, lme4_devianceSym, lme4_dimsSym, lme4_GpSym, lme4_STSym, Mer_sigma(), nf_POS, q_POS, and ST_nc_nlev().
SEXP mer_profiled_deviance (SEXP x)
Externally callable version of profiled_deviance.
See also:
profiled_deviance
Parameters:
x pointer to an mer object
Returns:
profiled deviance or REML deviance
Definition at line 1244 of file lmer.c.
References profiled_deviance().
SEXP mer_sigma (SEXP x, SEXP which)
Extract the estimate of the common scale factor from an mer object.
Parameters:
x an lmer object
which scalar integer (< 0 => REML, 0 => native, > 0 => ML)
Returns:
scalar REAL value
Definition at line 559 of file lmer.c.
References isREML, lme4_devianceSym, lme4_dimsSym, and Mer_sigma().
SEXP mer_ST_getPars (SEXP x)
Extract the parameters from the ST slot of an mer object.
Parameters:
x an mer object
Returns:
pointer to a REAL vector
Definition at line 415 of file lmer.c.
References lme4_dimsSym, np_POS, and ST_getPars().
SEXP mer_ST_initialize (SEXP ST, SEXP Gpp, SEXP Zt)
Evaluate starting estimates for the elements of ST.
Parameters:
ST pointers to the nf ST factorizations of the diagonal elements of Sigma
Gpp length nf+1 vector of group pointers for the rows of Zt
Zt transpose of Z matrix
Definition at line 313 of file lmer.c.
References Alloca, AZERO, lme4_DimSym, lme4_iSym, lme4_pSym, lme4_xSym, and ST_nc_nlev().
SEXP mer_ST_setPars (SEXP x, SEXP pars)
Update the ST slot of an mer object from a REAL vector of parameters and update the Cholesky factorization.
Parameters:
x an mer object
pars a REAL vector of the appropriate length
Returns:
R_NilValue
Definition at line 508 of file lmer.c.
References _, lme4_dimsSym, np_POS, and ST_setPars().
SEXP mer_update_dev (SEXP x)
Evaluate the discrepancy and log of the penalized discrepancy.
update_mu must be called first.
Parameters:
x pointer to an mer object
Definition at line 1030 of file lmer.c.
References _, disc_POS, fTyp_POS, ldL2_POS, lme4_devianceSym, lme4_dimsSym, lme4_muEtaSym, lme4_muSym, lme4_priorWtSym, lme4_ySym, ML_POS, n_POS, usqr_POS, wrss_POS, and y_log_y().
SEXP mer_update_effects (SEXP x)
Update the contents of the fixef, ranef and uvec slots in an lmer object.
Parameters:
x an lmer object
Returns:
R_NilValue
Definition at line 1079 of file lmer.c.
References _, c, disc_POS, L_SLOT, lme4_devianceSym, lme4_dimsSym, lme4_fixefSym, lme4_GpSym, lme4_muEtaSym, lme4_ranefSym, lme4_RVXySym, lme4_RXySym, lme4_STSym, lme4_uvecSym, lme4_vSym, lpdisc_POS, p_POS, q_POS, sqr_length(), TSPp_SEXP_mult(), and usqr_POS.
SEXP mer_update_L (SEXP x)
Externally callable version of update_L.
Update the A, L, sqrtWt and resid slots. It is assumed that update_mu has already been called at the current values of u and the model parameters.
Parameters:
x an mer object
Returns:
penalized weighted residual sum of squares
Definition at line 903 of file lmer.c.
References update_L().
SEXP mer_update_mu (SEXP x)
Externally callable update_mu.
Update the eta, v, mu, resid and var slots according to the current values of the parameters and u. Also evaluate d[wrss_POS] using the current sqrtWt slot. The sqrtWt slot is changed in update_L.
Parameters:
x pointer to an mer object
Returns:
penalized, weighted residual sum of squares
Definition at line 810 of file lmer.c.
References update_mu().
SEXP mer_validate (SEXP x)
Check validity of an object that inherits from the mer class.
Parameters:
x Pointer to an lmer or glmer or nlmer object
Returns:
TRUE if the object is a valid mer object, otherwise a string that describes the violation.
size of buffer for an error message
Definition at line 1625 of file lmer.c.
References _, Alloca, BUF_SIZE, chkDims(), cvg_POS, L_SLOT, lme4_devianceSym, lme4_dimsSym, lme4_etaSym, lme4_fixefSym, lme4_flistSym, lme4_GpSym, lme4_muEtaSym, lme4_muSym, lme4_offsetSym, lme4_priorWtSym, lme4_ranefSym, lme4_residSym, lme4_RVXySym, lme4_RXySym, lme4_STSym, lme4_uvecSym, lme4_vSym, lme4_VtSym, lme4_XSym, lme4_XytXySym, lme4_ySym, lme4_ZtSym, lme4_ZtXySym, n_POS, nf_POS, p_POS, q_POS, s_POS, and wrss_POS.
SEXP nlmer_create_A (SEXP Vt, SEXP sP)
Create the dgCMatrix object A.
Parameters:
Vt V' as a dgCMatrix object
sP pointer to the INTEGER object s
Definition at line 527 of file lmer.c.
References _, and c.
SEXP pedigree_chol (SEXP x, SEXP ans)
Create the left Cholesky factor of the numerator relationship matrix from a pedigree.
Parameters:
x a pedigree object
ans T stored as a non-unit, lower dtCMatrix
Returns:
ans with elements modified to incorporate D
Definition at line 1746 of file lmer.c.
References lme4_iSym, lme4_pSym, and lme4_xSym.