/** Pointers to symbols initialized in R_init_lme4 */
SEXP attribute_hidden
    lme4_DimSym,
    lme4_LSym,
    lme4_LambdaSym,
    lme4_LindSym,
    lme4_RXSym,
    lme4_RZXSym,
    lme4_UtSym,
    lme4_XSym,
    lme4_ZtSym,
    lme4_familySym,
    lme4_fixefSym,
    lme4_flistSym,
    lme4_gammaSym,
    lme4_ghwSym,
    lme4_ghxSym,
    lme4_iSym,
    lme4_ldL2Sym,
    lme4_muEtaSym,
    lme4_muSym,
    lme4_nlmodelSym,
    lme4_offsetSym,
    lme4_pSym,
    lme4_pwrssSym,
    lme4_sqrtrwtSym,
    lme4_sqrtXwtSym,
    lme4_thetaSym,
    lme4_uSym,
    lme4_varSym,
    lme4_weightsSym,
    lme4_xSym,
    lme4_ySym;

