#! /bin/bash
## install latest version of lme4
R CMD INSTALL -l ./library ../pkg/lme4
## set up proper testing environment
cp ~/.R/check.Renviron.bak ~/.R/check.Renviron
export R_LIBS_SITE=./library
## run tests
R CMD BATCH --vanilla lme4deptests.R
## tear down testing environment
rm ~/.R/check.Renviron
## cleanup
## rm -Rf *.Rcheck ## (?)